//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftInvBusiness.SoftInvWSProductoTipo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/", ConfigurationName="SoftInvWSProductoTipo.ProductosTipo")]
    public interface ProductosTipo {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softinvws.services.softinv.pucp.edu.pe/ProductosTipo/InsertarRequest", ReplyAction="http://softinvws.services.softinv.pucp.edu.pe/ProductosTipo/InsertarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuarioDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvBusiness.SoftInvWSProductoTipo.InsertarResponse Insertar(SoftInvBusiness.SoftInvWSProductoTipo.InsertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softinvws.services.softinv.pucp.edu.pe/ProductosTipo/InsertarRequest", ReplyAction="http://softinvws.services.softinv.pucp.edu.pe/ProductosTipo/InsertarResponse")]
        System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSProductoTipo.InsertarResponse> InsertarAsync(SoftInvBusiness.SoftInvWSProductoTipo.InsertarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softinvws.services.softinv.pucp.edu.pe/ProductosTipo/EliminarRequest", ReplyAction="http://softinvws.services.softinv.pucp.edu.pe/ProductosTipo/EliminarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuarioDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvBusiness.SoftInvWSProductoTipo.EliminarResponse Eliminar(SoftInvBusiness.SoftInvWSProductoTipo.EliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softinvws.services.softinv.pucp.edu.pe/ProductosTipo/EliminarRequest", ReplyAction="http://softinvws.services.softinv.pucp.edu.pe/ProductosTipo/EliminarResponse")]
        System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSProductoTipo.EliminarResponse> EliminarAsync(SoftInvBusiness.SoftInvWSProductoTipo.EliminarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softinvws.services.softinv.pucp.edu.pe/ProductosTipo/ModificarRequest", ReplyAction="http://softinvws.services.softinv.pucp.edu.pe/ProductosTipo/ModificarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuarioDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvBusiness.SoftInvWSProductoTipo.ModificarResponse Modificar(SoftInvBusiness.SoftInvWSProductoTipo.ModificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softinvws.services.softinv.pucp.edu.pe/ProductosTipo/ModificarRequest", ReplyAction="http://softinvws.services.softinv.pucp.edu.pe/ProductosTipo/ModificarResponse")]
        System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSProductoTipo.ModificarResponse> ModificarAsync(SoftInvBusiness.SoftInvWSProductoTipo.ModificarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softinvws.services.softinv.pucp.edu.pe/ProductosTipo/ObtenerProductosTipos" +
            "IdRequest", ReplyAction="http://softinvws.services.softinv.pucp.edu.pe/ProductosTipo/ObtenerProductosTipos" +
            "IdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuarioDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvBusiness.SoftInvWSProductoTipo.ObtenerProductosTiposIdResponse ObtenerProductosTiposId(SoftInvBusiness.SoftInvWSProductoTipo.ObtenerProductosTiposIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softinvws.services.softinv.pucp.edu.pe/ProductosTipo/ObtenerProductosTipos" +
            "IdRequest", ReplyAction="http://softinvws.services.softinv.pucp.edu.pe/ProductosTipo/ObtenerProductosTipos" +
            "IdResponse")]
        System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSProductoTipo.ObtenerProductosTiposIdResponse> ObtenerProductosTiposIdAsync(SoftInvBusiness.SoftInvWSProductoTipo.ObtenerProductosTiposIdRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/")]
    public partial class productoTipoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private bool activoFieldSpecified;
        
        private string ingredientesField;
        
        private productoDTO productoField;
        
        private int stock_despachoField;
        
        private bool stock_despachoFieldSpecified;
        
        private int stock_fisicoField;
        
        private bool stock_fisicoFieldSpecified;
        
        private string tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ingredientes {
            get {
                return this.ingredientesField;
            }
            set {
                this.ingredientesField = value;
                this.RaisePropertyChanged("ingredientes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public productoDTO producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int stock_despacho {
            get {
                return this.stock_despachoField;
            }
            set {
                this.stock_despachoField = value;
                this.RaisePropertyChanged("stock_despacho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stock_despachoSpecified {
            get {
                return this.stock_despachoFieldSpecified;
            }
            set {
                this.stock_despachoFieldSpecified = value;
                this.RaisePropertyChanged("stock_despachoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int stock_fisico {
            get {
                return this.stock_fisicoField;
            }
            set {
                this.stock_fisicoField = value;
                this.RaisePropertyChanged("stock_fisico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stock_fisicoSpecified {
            get {
                return this.stock_fisicoFieldSpecified;
            }
            set {
                this.stock_fisicoFieldSpecified = value;
                this.RaisePropertyChanged("stock_fisicoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/")]
    public partial class productoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private bool activoFieldSpecified;
        
        private comentarioDTO[] comentariosField;
        
        private string descripcionField;
        
        private int idProductoField;
        
        private bool idProductoFieldSpecified;
        
        private string modoUsoField;
        
        private string nombreField;
        
        private double precioField;
        
        private bool precioFieldSpecified;
        
        private productoTipoDTO[] productosTiposField;
        
        private double promedioValoracionField;
        
        private bool promedioValoracionFieldSpecified;
        
        private double tamanhoField;
        
        private bool tamanhoFieldSpecified;
        
        private string urlImagenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("comentarios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public comentarioDTO[] comentarios {
            get {
                return this.comentariosField;
            }
            set {
                this.comentariosField = value;
                this.RaisePropertyChanged("comentarios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProductoSpecified {
            get {
                return this.idProductoFieldSpecified;
            }
            set {
                this.idProductoFieldSpecified = value;
                this.RaisePropertyChanged("idProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string modoUso {
            get {
                return this.modoUsoField;
            }
            set {
                this.modoUsoField = value;
                this.RaisePropertyChanged("modoUso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioSpecified {
            get {
                return this.precioFieldSpecified;
            }
            set {
                this.precioFieldSpecified = value;
                this.RaisePropertyChanged("precioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("productosTipos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public productoTipoDTO[] productosTipos {
            get {
                return this.productosTiposField;
            }
            set {
                this.productosTiposField = value;
                this.RaisePropertyChanged("productosTipos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double promedioValoracion {
            get {
                return this.promedioValoracionField;
            }
            set {
                this.promedioValoracionField = value;
                this.RaisePropertyChanged("promedioValoracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool promedioValoracionSpecified {
            get {
                return this.promedioValoracionFieldSpecified;
            }
            set {
                this.promedioValoracionFieldSpecified = value;
                this.RaisePropertyChanged("promedioValoracionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double tamanho {
            get {
                return this.tamanhoField;
            }
            set {
                this.tamanhoField = value;
                this.RaisePropertyChanged("tamanho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tamanhoSpecified {
            get {
                return this.tamanhoFieldSpecified;
            }
            set {
                this.tamanhoFieldSpecified = value;
                this.RaisePropertyChanged("tamanhoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string urlImagen {
            get {
                return this.urlImagenField;
            }
            set {
                this.urlImagenField = value;
                this.RaisePropertyChanged("urlImagen");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/")]
    public partial class comentarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private clienteDTO clienteField;
        
        private string comentarioField;
        
        private int idComentarioField;
        
        private bool idComentarioFieldSpecified;
        
        private productoDTO productoField;
        
        private servicioDTO servicioField;
        
        private int valoracionField;
        
        private bool valoracionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public clienteDTO cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string comentario {
            get {
                return this.comentarioField;
            }
            set {
                this.comentarioField = value;
                this.RaisePropertyChanged("comentario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idComentario {
            get {
                return this.idComentarioField;
            }
            set {
                this.idComentarioField = value;
                this.RaisePropertyChanged("idComentario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idComentarioSpecified {
            get {
                return this.idComentarioFieldSpecified;
            }
            set {
                this.idComentarioFieldSpecified = value;
                this.RaisePropertyChanged("idComentarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public productoDTO producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public servicioDTO servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
                this.RaisePropertyChanged("servicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int valoracion {
            get {
                return this.valoracionField;
            }
            set {
                this.valoracionField = value;
                this.RaisePropertyChanged("valoracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valoracionSpecified {
            get {
                return this.valoracionFieldSpecified;
            }
            set {
                this.valoracionFieldSpecified = value;
                this.RaisePropertyChanged("valoracionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/")]
    public partial class clienteDTO : usuarioDTO {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(empleadoDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clienteDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/")]
    public abstract partial class usuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private bool activoFieldSpecified;
        
        private string celularField;
        
        private string contrasenhaField;
        
        private string correoElectronicoField;
        
        private int idUsuarioField;
        
        private bool idUsuarioFieldSpecified;
        
        private string nombreField;
        
        private string primerapellidoField;
        
        private string segundoapellidoField;
        
        private string urlFotoPerfilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
                this.RaisePropertyChanged("celular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string contrasenha {
            get {
                return this.contrasenhaField;
            }
            set {
                this.contrasenhaField = value;
                this.RaisePropertyChanged("contrasenha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                this.correoElectronicoField = value;
                this.RaisePropertyChanged("correoElectronico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUsuarioSpecified {
            get {
                return this.idUsuarioFieldSpecified;
            }
            set {
                this.idUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("idUsuarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string primerapellido {
            get {
                return this.primerapellidoField;
            }
            set {
                this.primerapellidoField = value;
                this.RaisePropertyChanged("primerapellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string segundoapellido {
            get {
                return this.segundoapellidoField;
            }
            set {
                this.segundoapellidoField = value;
                this.RaisePropertyChanged("segundoapellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string urlFotoPerfil {
            get {
                return this.urlFotoPerfilField;
            }
            set {
                this.urlFotoPerfilField = value;
                this.RaisePropertyChanged("urlFotoPerfil");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/")]
    public partial class time : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/")]
    public partial class date : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/")]
    public partial class citaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private bool activoFieldSpecified;
        
        private clienteDTO clienteField;
        
        private string codigoTransaccionField;
        
        private empleadoDTO empleadoField;
        
        private date fechaField;
        
        private time horaFinField;
        
        private time horaIniField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private double igvField;
        
        private bool igvFieldSpecified;
        
        private servicioDTO servicioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public clienteDTO cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoTransaccion {
            get {
                return this.codigoTransaccionField;
            }
            set {
                this.codigoTransaccionField = value;
                this.RaisePropertyChanged("codigoTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public empleadoDTO empleado {
            get {
                return this.empleadoField;
            }
            set {
                this.empleadoField = value;
                this.RaisePropertyChanged("empleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public date fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public time horaFin {
            get {
                return this.horaFinField;
            }
            set {
                this.horaFinField = value;
                this.RaisePropertyChanged("horaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public time horaIni {
            get {
                return this.horaIniField;
            }
            set {
                this.horaIniField = value;
                this.RaisePropertyChanged("horaIni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double igv {
            get {
                return this.igvField;
            }
            set {
                this.igvField = value;
                this.RaisePropertyChanged("igv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool igvSpecified {
            get {
                return this.igvFieldSpecified;
            }
            set {
                this.igvFieldSpecified = value;
                this.RaisePropertyChanged("igvSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public servicioDTO servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
                this.RaisePropertyChanged("servicio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/")]
    public partial class empleadoDTO : usuarioDTO {
        
        private bool adminField;
        
        private bool adminFieldSpecified;
        
        private servicioDTO[] serviciosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool admin {
            get {
                return this.adminField;
            }
            set {
                this.adminField = value;
                this.RaisePropertyChanged("admin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adminSpecified {
            get {
                return this.adminFieldSpecified;
            }
            set {
                this.adminFieldSpecified = value;
                this.RaisePropertyChanged("adminSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("servicios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public servicioDTO[] servicios {
            get {
                return this.serviciosField;
            }
            set {
                this.serviciosField = value;
                this.RaisePropertyChanged("servicios");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/")]
    public partial class servicioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private bool activoFieldSpecified;
        
        private citaDTO[] citasField;
        
        private comentarioDTO[] comentariosField;
        
        private string descripcionField;
        
        private int duracionHoraField;
        
        private bool duracionHoraFieldSpecified;
        
        private empleadoDTO[] empleadosField;
        
        private int idServicioField;
        
        private bool idServicioFieldSpecified;
        
        private string nombreField;
        
        private double precioField;
        
        private bool precioFieldSpecified;
        
        private double promedioValoracionField;
        
        private bool promedioValoracionFieldSpecified;
        
        private string tipoField;
        
        private string urlImagenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("citas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public citaDTO[] citas {
            get {
                return this.citasField;
            }
            set {
                this.citasField = value;
                this.RaisePropertyChanged("citas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("comentarios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public comentarioDTO[] comentarios {
            get {
                return this.comentariosField;
            }
            set {
                this.comentariosField = value;
                this.RaisePropertyChanged("comentarios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int duracionHora {
            get {
                return this.duracionHoraField;
            }
            set {
                this.duracionHoraField = value;
                this.RaisePropertyChanged("duracionHora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool duracionHoraSpecified {
            get {
                return this.duracionHoraFieldSpecified;
            }
            set {
                this.duracionHoraFieldSpecified = value;
                this.RaisePropertyChanged("duracionHoraSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("empleados", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public empleadoDTO[] empleados {
            get {
                return this.empleadosField;
            }
            set {
                this.empleadosField = value;
                this.RaisePropertyChanged("empleados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idServicio {
            get {
                return this.idServicioField;
            }
            set {
                this.idServicioField = value;
                this.RaisePropertyChanged("idServicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idServicioSpecified {
            get {
                return this.idServicioFieldSpecified;
            }
            set {
                this.idServicioFieldSpecified = value;
                this.RaisePropertyChanged("idServicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioSpecified {
            get {
                return this.precioFieldSpecified;
            }
            set {
                this.precioFieldSpecified = value;
                this.RaisePropertyChanged("precioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double promedioValoracion {
            get {
                return this.promedioValoracionField;
            }
            set {
                this.promedioValoracionField = value;
                this.RaisePropertyChanged("promedioValoracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool promedioValoracionSpecified {
            get {
                return this.promedioValoracionFieldSpecified;
            }
            set {
                this.promedioValoracionFieldSpecified = value;
                this.RaisePropertyChanged("promedioValoracionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string urlImagen {
            get {
                return this.urlImagenField;
            }
            set {
                this.urlImagenField = value;
                this.RaisePropertyChanged("urlImagen");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insertar", WrapperNamespace="http://softinvws.services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class InsertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvBusiness.SoftInvWSProductoTipo.productoTipoDTO productoTipo;
        
        public InsertarRequest() {
        }
        
        public InsertarRequest(SoftInvBusiness.SoftInvWSProductoTipo.productoTipoDTO productoTipo) {
            this.productoTipo = productoTipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertarResponse", WrapperNamespace="http://softinvws.services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class InsertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public InsertarResponse() {
        }
        
        public InsertarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Eliminar", WrapperNamespace="http://softinvws.services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class EliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvBusiness.SoftInvWSProductoTipo.productoTipoDTO productoTipo;
        
        public EliminarRequest() {
        }
        
        public EliminarRequest(SoftInvBusiness.SoftInvWSProductoTipo.productoTipoDTO productoTipo) {
            this.productoTipo = productoTipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarResponse", WrapperNamespace="http://softinvws.services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class EliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public EliminarResponse() {
        }
        
        public EliminarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Modificar", WrapperNamespace="http://softinvws.services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class ModificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvBusiness.SoftInvWSProductoTipo.productoTipoDTO productoTipo;
        
        public ModificarRequest() {
        }
        
        public ModificarRequest(SoftInvBusiness.SoftInvWSProductoTipo.productoTipoDTO productoTipo) {
            this.productoTipo = productoTipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModificarResponse", WrapperNamespace="http://softinvws.services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class ModificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public ModificarResponse() {
        }
        
        public ModificarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerProductosTiposId", WrapperNamespace="http://softinvws.services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class ObtenerProductosTiposIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProducto;
        
        public ObtenerProductosTiposIdRequest() {
        }
        
        public ObtenerProductosTiposIdRequest(int idProducto) {
            this.idProducto = idProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerProductosTiposIdResponse", WrapperNamespace="http://softinvws.services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class ObtenerProductosTiposIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvBusiness.SoftInvWSProductoTipo.productoTipoDTO[] @return;
        
        public ObtenerProductosTiposIdResponse() {
        }
        
        public ObtenerProductosTiposIdResponse(SoftInvBusiness.SoftInvWSProductoTipo.productoTipoDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductosTipoChannel : SoftInvBusiness.SoftInvWSProductoTipo.ProductosTipo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductosTipoClient : System.ServiceModel.ClientBase<SoftInvBusiness.SoftInvWSProductoTipo.ProductosTipo>, SoftInvBusiness.SoftInvWSProductoTipo.ProductosTipo {
        
        public ProductosTipoClient() {
        }
        
        public ProductosTipoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductosTipoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosTipoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosTipoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvBusiness.SoftInvWSProductoTipo.InsertarResponse SoftInvBusiness.SoftInvWSProductoTipo.ProductosTipo.Insertar(SoftInvBusiness.SoftInvWSProductoTipo.InsertarRequest request) {
            return base.Channel.Insertar(request);
        }
        
        public int Insertar(SoftInvBusiness.SoftInvWSProductoTipo.productoTipoDTO productoTipo) {
            SoftInvBusiness.SoftInvWSProductoTipo.InsertarRequest inValue = new SoftInvBusiness.SoftInvWSProductoTipo.InsertarRequest();
            inValue.productoTipo = productoTipo;
            SoftInvBusiness.SoftInvWSProductoTipo.InsertarResponse retVal = ((SoftInvBusiness.SoftInvWSProductoTipo.ProductosTipo)(this)).Insertar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSProductoTipo.InsertarResponse> SoftInvBusiness.SoftInvWSProductoTipo.ProductosTipo.InsertarAsync(SoftInvBusiness.SoftInvWSProductoTipo.InsertarRequest request) {
            return base.Channel.InsertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSProductoTipo.InsertarResponse> InsertarAsync(SoftInvBusiness.SoftInvWSProductoTipo.productoTipoDTO productoTipo) {
            SoftInvBusiness.SoftInvWSProductoTipo.InsertarRequest inValue = new SoftInvBusiness.SoftInvWSProductoTipo.InsertarRequest();
            inValue.productoTipo = productoTipo;
            return ((SoftInvBusiness.SoftInvWSProductoTipo.ProductosTipo)(this)).InsertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvBusiness.SoftInvWSProductoTipo.EliminarResponse SoftInvBusiness.SoftInvWSProductoTipo.ProductosTipo.Eliminar(SoftInvBusiness.SoftInvWSProductoTipo.EliminarRequest request) {
            return base.Channel.Eliminar(request);
        }
        
        public int Eliminar(SoftInvBusiness.SoftInvWSProductoTipo.productoTipoDTO productoTipo) {
            SoftInvBusiness.SoftInvWSProductoTipo.EliminarRequest inValue = new SoftInvBusiness.SoftInvWSProductoTipo.EliminarRequest();
            inValue.productoTipo = productoTipo;
            SoftInvBusiness.SoftInvWSProductoTipo.EliminarResponse retVal = ((SoftInvBusiness.SoftInvWSProductoTipo.ProductosTipo)(this)).Eliminar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSProductoTipo.EliminarResponse> SoftInvBusiness.SoftInvWSProductoTipo.ProductosTipo.EliminarAsync(SoftInvBusiness.SoftInvWSProductoTipo.EliminarRequest request) {
            return base.Channel.EliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSProductoTipo.EliminarResponse> EliminarAsync(SoftInvBusiness.SoftInvWSProductoTipo.productoTipoDTO productoTipo) {
            SoftInvBusiness.SoftInvWSProductoTipo.EliminarRequest inValue = new SoftInvBusiness.SoftInvWSProductoTipo.EliminarRequest();
            inValue.productoTipo = productoTipo;
            return ((SoftInvBusiness.SoftInvWSProductoTipo.ProductosTipo)(this)).EliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvBusiness.SoftInvWSProductoTipo.ModificarResponse SoftInvBusiness.SoftInvWSProductoTipo.ProductosTipo.Modificar(SoftInvBusiness.SoftInvWSProductoTipo.ModificarRequest request) {
            return base.Channel.Modificar(request);
        }
        
        public int Modificar(SoftInvBusiness.SoftInvWSProductoTipo.productoTipoDTO productoTipo) {
            SoftInvBusiness.SoftInvWSProductoTipo.ModificarRequest inValue = new SoftInvBusiness.SoftInvWSProductoTipo.ModificarRequest();
            inValue.productoTipo = productoTipo;
            SoftInvBusiness.SoftInvWSProductoTipo.ModificarResponse retVal = ((SoftInvBusiness.SoftInvWSProductoTipo.ProductosTipo)(this)).Modificar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSProductoTipo.ModificarResponse> SoftInvBusiness.SoftInvWSProductoTipo.ProductosTipo.ModificarAsync(SoftInvBusiness.SoftInvWSProductoTipo.ModificarRequest request) {
            return base.Channel.ModificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSProductoTipo.ModificarResponse> ModificarAsync(SoftInvBusiness.SoftInvWSProductoTipo.productoTipoDTO productoTipo) {
            SoftInvBusiness.SoftInvWSProductoTipo.ModificarRequest inValue = new SoftInvBusiness.SoftInvWSProductoTipo.ModificarRequest();
            inValue.productoTipo = productoTipo;
            return ((SoftInvBusiness.SoftInvWSProductoTipo.ProductosTipo)(this)).ModificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvBusiness.SoftInvWSProductoTipo.ObtenerProductosTiposIdResponse SoftInvBusiness.SoftInvWSProductoTipo.ProductosTipo.ObtenerProductosTiposId(SoftInvBusiness.SoftInvWSProductoTipo.ObtenerProductosTiposIdRequest request) {
            return base.Channel.ObtenerProductosTiposId(request);
        }
        
        public SoftInvBusiness.SoftInvWSProductoTipo.productoTipoDTO[] ObtenerProductosTiposId(int idProducto) {
            SoftInvBusiness.SoftInvWSProductoTipo.ObtenerProductosTiposIdRequest inValue = new SoftInvBusiness.SoftInvWSProductoTipo.ObtenerProductosTiposIdRequest();
            inValue.idProducto = idProducto;
            SoftInvBusiness.SoftInvWSProductoTipo.ObtenerProductosTiposIdResponse retVal = ((SoftInvBusiness.SoftInvWSProductoTipo.ProductosTipo)(this)).ObtenerProductosTiposId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSProductoTipo.ObtenerProductosTiposIdResponse> SoftInvBusiness.SoftInvWSProductoTipo.ProductosTipo.ObtenerProductosTiposIdAsync(SoftInvBusiness.SoftInvWSProductoTipo.ObtenerProductosTiposIdRequest request) {
            return base.Channel.ObtenerProductosTiposIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSProductoTipo.ObtenerProductosTiposIdResponse> ObtenerProductosTiposIdAsync(int idProducto) {
            SoftInvBusiness.SoftInvWSProductoTipo.ObtenerProductosTiposIdRequest inValue = new SoftInvBusiness.SoftInvWSProductoTipo.ObtenerProductosTiposIdRequest();
            inValue.idProducto = idProducto;
            return ((SoftInvBusiness.SoftInvWSProductoTipo.ProductosTipo)(this)).ObtenerProductosTiposIdAsync(inValue);
        }
    }
}
